name: chewie
description: A video player for Flutter with Cupertino and Material play controls
version: 1.7.1
homepage: https://github.com/fluttercommunity/chewie

environment:
  sdk: ">=3.1.4 <4.0.0"
  flutter: ">=3.13.8"

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  provider: ^6.0.5
  video_player: ^2.8.1
  wakelock_plus: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
